language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

os:
  - linux
  - osx

env:
  global:
    - QT_VERSION=qt:5.6.1
    - QT_VERSION=qt:5.7.0
    # - QT_DIR="${TRAVIS_BUILD_DIR}/vendor/qt5"

services:
  - docker

addons:
  apt:
    packages:
      - xvfb


# Test libqmlbind-sys only for now
script:
  # - sh -c 'cd libqmlbind-sys && cargo build --verbose'
  # Ignore error from cargo
  - sh -c 'cd libqmlbind-sys && cargo build --verbose ||:'
  - find . -name "libqmlbind*"
  - ls libqmlbind-sys/libqmlbind/qmlbind
  - tree
  # Force failure
  - sh -c 'exit 1'
