language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

os:
  - linux
  # - osx

before_install:
  # - sudo add-apt-repository ppa:beineri/opt-qt56 -y
  - sudo add-apt-repository ppa:beineri/opt-qt57 -y
install:
  # - sudo apt-get install qt56-meta qt56base
  - sudo apt-get install qt57-meta qt57base


# Test libqmlbind-sys only for now
script:
  # - sh -c 'cd libqmlbind-sys && cargo build --verbose'
  # Ignore error from cargo
    # - QT_DIR="${TRAVIS_BUILD_DIR}/vendor/qt5"
  - source /opt/qt57/bin/qt57-env.sh
  - sh -c 'cd libqmlbind-sys && cargo build --verbose'
  # - sh -c 'cd libqmlbind-sys && cargo build --verbose ||:'
  - find . -name "libqmlbind*" | sort
  - ls libqmlbind-sys/libqmlbind/qmlbind
  - ls libqmlbind-sys/libqmlbind/build
  # Force failure
  # - sh -c 'exit 1'
