language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  exclude:
    # Homebrew on OSX is not yet at 5.7
    - os: osx
      env: QT_BASE=57


sudo: required
dist: trusty

env:
  - QT_BASE=561
  - QT_BASE=57

os:
  - linux
  - osx

before_install:
  # 561 --> 56
  - export QT_VER=${QT_BASE:0:2}
  # 561 --> 5.6.1
  - export QT_BASE_DOT=`echo ${QT_BASE} | sed 's/\(.\)/\1./g;s/\.$//'`

install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then sudo add-apt-repository -y ppa:beineri/opt-qt${QT_BASE}-trusty; fi
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then sudo apt-get update; fi
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then sudo apt-get -y install qt${QT_VER}quickcontrols qt${QT_VER}quickcontrols2; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then   brew update; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then   brew install qt5; fi


# Test libqmlbind-sys only for now
script:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then source /opt/qt${QT_VER}/bin/qt${QT_VER}-env.sh; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then   export QT_DIR=/usr/local/Cellar/qt5/${QT_BASE_DOT}/; fi
  - sh -c 'cd libqmlbind-sys && cargo build --verbose'
